### ISSUE TITLE
cons doesn't work, missing ITrack.h file

### ISSUE THREAD

**Issue by cracz** [cracz/TreeAnalysis#9]
Looks like the StRoot/IClasses stuff needs another file (ITrack.h) for "cons" to work. This command is necessary for all of the other components in StRoot.

**Comment by ErikMLoyd** [comment]
That is an artifact from old classes that are now unused. I've removed the reference in the header; it should work now.

**Comment by cracz** [comment]
Ran into some more issues. First couple are easy:

IEvent.h and IEvent.cxx each have one instance of "IEventPLane" with capital L
"#include "TMath.h"" seems to be necessary in IEvent.cxx

The rest of the problems are with some functions from IEventPlane that don't seem to exist within that class. The errors from cons showing which functions can't be found is attached.
[consErrors.txt](https://github.com/cracz/TreeAnalysis/files/7962914/consErrors.txt)

**Comment by ErikMLoyd** [comment]
Fixed most of the things. I'm assuming the rest of those things came about because of those former errors.

When I do cons myself, I get no errors whatsoever, so I can't seem the check the validity.

**Comment by cracz** [comment]
I figured out the last few problems and updated the files. 

IEvent.cxx: changed "mEPParticlesCopy.Add(newParticle)" to "mEPParticlesCopy.push_back(newParticle)"

IEventPlane.cxx: mRingNumber wasn't declared, mTileID and nMIP were commented out so these are fixed. Also changed "f in_weight" to "float in_weight".
